# Generated by Django 3.0.8 on 2020-07-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Due_Date', models.DateTimeField()),
                ('Title', models.CharField(max_length=128)),
                ('Text', models.TextField()),
            ],
        ),
    ]
